---
# tasks file for docker-registry
- name: login dockerhub
  docker_login:
    username: "amineounissi"
    password: "amine2022"
- name: push to dockerhub
  docker_image:
    name: devops:latest
    repository: amineounissi/my-repo2
    push: yes
    source: local
